import type { TranslationKeys } from './en';

export const ar: TranslationKeys = {
  common: { save: 'حفظ', cancel: 'إلغاء', delete: 'حذف', edit: 'تعديل', add: 'إضافة', search: 'بحث', loading: 'جاري التحميل...', submit: 'إرسال', close: 'إغلاق', back: 'رجوع', next: 'التالي', previous: 'السابق', confirm: 'تأكيد', yes: 'نعم', no: 'لا', required: 'مطلوب', optional: 'اختياري', all: 'الكل', none: 'لا شيء', settings: 'الإعدادات', logout: 'تسجيل خروج', login: 'تسجيل دخول' },
  nav: { dashboard: 'لوحة التحكم', quotations: 'عروض الأسعار', customers: 'العملاء', products: 'المنتجات', users: 'المستخدمين', reports: 'التقارير', approvals: 'الموافقات', commissions: 'العمولات', targets: 'الأهداف', notifications: 'الإشعارات', settings: 'الإعدادات' },
  auth: { email: 'البريد الإلكتروني', password: 'كلمة المرور', signIn: 'تسجيل الدخول', signOut: 'تسجيل الخروج', dontHaveAccount: 'ليس لديك حساب؟', requestAccount: 'طلب إنشاء حساب', fillForm: 'املأ النموذج وسيوافق المسؤول', accountRequest: 'طلب حساب', backToLogin: 'العودة للدخول', fullName: 'الاسم الكامل', phone: 'رقم الهاتف', department: 'القسم', requestedRole: 'الدور المطلوب', confirmPassword: 'تأكيد كلمة المرور', submitRequest: 'إرسال الطلب', adminWillReview: 'سيقوم المسؤول بالمراجعة', accountWillBeReviewed: 'ستتم مراجعة حسابك', passwordMinLength: 'الحد الأدنى 6 أحرف', reenterPassword: 'إعادة إدخال كلمة المرور' },
  roles: { admin: 'مسؤول النظام', sales: 'مندوب مبيعات', manager: 'مدير المبيعات', engineering: 'فريق الهندسة', finance: 'فريق المالية', ceo: 'المدير التنفيذي' },
  dashboard: { welcome: 'مرحباً بعودتك', overview: 'نظرة عامة', recentActivity: 'النشاط الأخير', statistics: 'الإحصائيات', performance: 'الأداء' },
  quotations: { title: 'عروض الأسعار', subtitle: 'إنشاء وإدارة عروض الأسعار', createNew: 'إنشاء عرض سعر', quotationNumber: 'رقم عرض السعر', customer: 'العميل', status: 'الحالة', totalAmount: 'المبلغ الإجمالي', createdBy: 'أنشئ بواسطة', createdAt: 'تاريخ الإنشاء', validUntil: 'صالح حتى', items: 'العناصر', addItem: 'إضافة عنصر', discount: 'الخصم', tax: 'الضريبة', subtotal: 'المجموع الفرعي', total: 'المجموع', notes: 'ملاحظات', selectCustomer: 'اختر العميل', selectProduct: 'اختر المنتج', quantity: 'الكمية', unitPrice: 'سعر الوحدة', statuses: { draft: 'مسودة', pending_manager: 'بانتظار المدير', pending_engineering: 'بانتظار الهندسة', pending_ceo: 'بانتظار المدير التنفيذي', pending_finance: 'بانتظار المالية', approved: 'موافق عليه', rejected: 'مرفوض', submitted_to_customer: 'مُرسل للعميل', deal_won: 'تم إغلاق الصفقة', deal_lost: 'خسارة الصفقة' } },
  customers: { title: 'العملاء', subtitle: 'إدارة قاعدة بيانات العملاء', addCustomer: 'إضافة عميل', companyName: 'اسم الشركة', contactPerson: 'الشخص المسؤول', email: 'البريد الإلكتروني', phone: 'الهاتف', address: 'العنوان', city: 'المدينة', country: 'الدولة', taxId: 'الرقم الضريبي', customerType: 'نوع العميل', sector: 'القطاع', notes: 'ملاحظات', createdBy: 'أنشئ بواسطة', importCSV: 'استيراد CSV', exportCSV: 'تصدير CSV', csvImportFormat: 'صيغة CSV', csvFormatDescription: 'صيغة ملف CSV', csvFormatColumns: 'اسم الشركة، الشخص المسؤول، البريد', firstRowHeaders: 'الصف الأول عناوين', customerTypes: { direct_sales: 'مبيعات مباشرة', partner: 'شريك', distributor: 'موزع' }, sectors: { government: 'حكومي', financial: 'مالي', telecommunications: 'اتصالات', corporate_private: 'شركات خاصة', healthcare: 'رعاية صحية', education: 'تعليم', hospitality: 'ضيافة', startups_tech: 'شركات ناشئة' } },
  products: { title: 'المنتجات', subtitle: 'إدارة كتالوج المنتجات', addProduct: 'إضافة منتج', productName: 'اسم المنتج', sku: 'رمز المنتج', description: 'الوصف', category: 'الفئة', basePrice: 'السعر الأساسي', cost: 'التكلفة', stockQuantity: 'كمية المخزون', minStockLevel: 'الحد الأدنى', isActive: 'نشط', specifications: 'المواصفات', importCSV: 'استيراد', exportCSV: 'تصدير' },
  users: { title: 'المستخدمين', subtitle: 'إدارة مستخدمي النظام', addUser: 'إضافة مستخدم', fullName: 'الاسم الكامل', email: 'البريد الإلكتروني', role: 'الدور', department: 'القسم', phone: 'الهاتف', status: 'الحالة', active: 'نشط', inactive: 'غير نشط', salesTarget: 'هدف المبيعات' },
  reports: { title: 'التقارير', subtitle: 'التحليلات والرؤى', salesReport: 'تقرير المبيعات', performanceReport: 'تقرير الأداء', customerReport: 'تقرير العملاء', productReport: 'تقرير المنتجات', dateRange: 'النطاق الزمني', from: 'من', to: 'إلى', generate: 'إنشاء', export: 'تصدير' },
  approvals: { title: 'الموافقات', subtitle: 'مراجعة عروض الأسعار', pendingApproval: 'بانتظار الموافقة', approve: 'موافقة', reject: 'رفض', requestChanges: 'طلب تعديلات', approvalHistory: 'سجل الموافقات', comments: 'التعليقات', addComment: 'إضافة تعليق' },
  commissions: { title: 'العمولات', subtitle: 'تتبع عمولات المبيعات', totalCommission: 'إجمالي العمولة', paidCommission: 'العمولة المدفوعة', pendingCommission: 'العمولة المعلقة', commissionRate: 'نسبة العمولة', period: 'الفترة', salesAmount: 'مبلغ المبيعات' },
  targets: { title: 'أهداف المبيعات', subtitle: 'إدارة الأهداف', setTarget: 'تحديد الهدف', targetAmount: 'مبلغ الهدف', achieved: 'المحقق', remaining: 'المتبقي', progress: 'التقدم', monthly: 'شهري', quarterly: 'ربع سنوي', yearly: 'سنوي' },
  notifications: { title: 'الإشعارات', subtitle: 'إشعاراتك', markAllRead: 'تحديد الكل كمقروء', noNotifications: 'لا توجد إشعارات', newQuotation: 'عرض سعر جديد', quotationApproved: 'موافقة على عرض السعر', quotationRejected: 'رفض عرض السعر' },
  settings: { title: 'الإعدادات', subtitle: 'تكوين التفضيلات', profile: 'الملف الشخصي', language: 'اللغة', theme: 'السمة', notifications: 'الإشعارات', security: 'الأمان', changePassword: 'تغيير كلمة المرور', currentPassword: 'كلمة المرور الحالية', newPassword: 'كلمة المرور الجديدة', selectLanguage: 'اختر اللغة', english: 'الإنجليزية', arabic: 'العربية (السعودية)' },
  messages: { success: 'نجح', error: 'خطأ', confirmDelete: 'هل أنت متأكد من الحذف؟', saveSuccess: 'تم الحفظ بنجاح', deleteSuccess: 'تم الحذف بنجاح', updateSuccess: 'تم التحديث بنجاح', createSuccess: 'تم الإنشاء بنجاح', loadError: 'فشل التحميل', saveError: 'فشل الحفظ', deleteError: 'فشل الحذف' },
};
